Push assets to github on release
ercole-io/ercole pull request #824
Opened 2022-03-02 13:03 UTC by cbiglioli

Fix #617 Update continuos integration flow

2022-03-07 10:24 UTC, cirelli94 commented
There are some conflicts that must be resolved, would you mind?
Don't insert commits too generics like "refactoring", please, use `commit --amend` and `push --force` if needed!
You commit here aren't readable! 
I don't like "617_Update_Continuos_Integration_flow" message and the "refactoring" or "fix" message is really not clear at all!

2022-03-07 10:24 UTC, cirelli94 requested changes
There are some conflicts that must be resolved, would you mind?
Don't insert commits too generics like "refactoring", please, use `commit --amend` and `push --force` if needed!
Your commit here aren't readable! 
I don't like "617_Update_Continuos_Integration_flow" message and the "refactoring" or "fix" message is really not clear at all!

2022-03-07 16:08 UTC, cbiglioli commented
> Refactoring--> changed steps name in task_deploy_repository



> There are some conflicts that must be resolved, would you mind? Don't insert commits too generics like "refactoring", please, use `commit --amend` and `push --force` if needed! Your commit here aren't readable! I don't like "617_Update_Continuos_Integration_flow" message and the "refactoring" or "fix" message is really not clear at all!

I'm sorry, but I think that is very clear: first of all I haven't any message with "fix" and I have only message with "refactoring" and you clearly see that it's explained why --> **changed steps name in task_deploy_repository**

2022-03-08 11:40 UTC, cirelli94 approved these changes

2022-03-08 11:40 UTC, merged